AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The User service is part of the ACME Serverless Shop. The goal of this specific service is to register and authenticate users using JWT tokens.

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        REGION: !Ref AWS::Region
        WAVEFRONT_ENABLED: true
        WAVEFRONT_URL: !Ref WavefrontURL
        WAVEFRONT_API_TOKEN: !Ref WavefrontToken

Parameters:
  Version:
    Type: String
  User:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev
  WavefrontURL:
    Type: String
  WavefrontToken:
    Type: String

Resources:
  UserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "10"
      TableName: "User"
  Register:
    Type: AWS::Serverless::Function
    Properties:
      Handler: register
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: Register
      Description: A Lambda function to register new users in DynamoDB
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /register
            Method: POST
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
Outputs:  
  UserTableARN:
    Description: ARN for the User DynamoDB Table
    Value: !GetAtt UserTable.Arn
  RegisterURL:
    Description: "API Gateway endpoint URL to register users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/"