AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The User service is part of the ACME Serverless Shop. The goal of this specific service is to register and authenticate users using JWT tokens.

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        REGION: !Ref AWS::Region
        WAVEFRONT_ENABLED: true
        WAVEFRONT_URL: !Ref WavefrontURL
        WAVEFRONT_API_TOKEN: !Ref WavefrontToken

Parameters:
  Version:
    Type: String
  User:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev
  WavefrontURL:
    Type: String
  WavefrontToken:
    Type: String

Resources:
  UserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "ID"
          AttributeType: "S"
        - AttributeName: "UserName"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "10"
      TableName: "User"
      GlobalSecondaryIndexes: 
        - IndexName: "UserName"
          KeySchema: 
            - AttributeName: "UserName"
              KeyType: "HASH"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "10"
            WriteCapacityUnits: "10"
  Register:
    Type: AWS::Serverless::Function
    Properties:
      Handler: register
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: Register
      Description: A Lambda function to register new users in DynamoDB
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        RegisterAPI:
          Type: Api
          Properties:
            Path: /register
            Method: POST
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  AllUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: allusers
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: AllUsers
      Description: A Lambda function to get all users from DynamoDB
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        AllUsersAPI:
          Type: Api
          Properties:
            Path: /users
            Method: GET
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getuser
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: GetUser
      Description: A Lambda function to get a user from DynamoDB
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        AllUsersAPI:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  Login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: login
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: Login
      Description: A Lambda function to login
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        RegisterAPI:
          Type: Api
          Properties:
            Path: /login
            Method: POST
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  VerifyToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: verifytoken
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: VerifyToken
      Description: A Lambda function to verify a JWT token
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
      Environment:
        Variables:
          TABLENAME: !Ref UserTable
      Events:
        RegisterAPI:
          Type: Api
          Properties:
            Path: /verify-token
            Method: POST
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
Outputs:  
  UserTableARN:
    Description: ARN for the User DynamoDB Table
    Value: !GetAtt UserTable.Arn
  RegisterURL:
    Description: "API Gateway endpoint URL to register users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/"
  AllUsersURL:
    Description: "API Gateway endpoint URL to get all users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  GetUserURL:
    Description: "API Gateway endpoint URL to get a user"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/{id}"
  LoginURL:
    Description: "API Gateway endpoint URL to login"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"
  VerifyTokenURL:
    Description: "API Gateway endpoint URL to verify the token"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/verify-token/"